name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.16.0
      - name: Install packages
        run: npm ci
      - name: Run code Linter
        run: npm run format:check
      - name: Run Code Analysis
        run: npm run lint
      - name: Run Tests
        run: npm test
